# Generated by Django 3.2.4 on 2021-06-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfiles',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='client_upload',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.clientfiles'),
            preserve_default=False,
        ),
    ]
