# Generated by Django 3.2.4 on 2021-06-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientfiles_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfiles',
            name='filename',
        ),
    ]
